Repository JCSDA-internal/ioda-data, pull requests merged in 2023-09, with the labels that each got.

#166 Add varno 295 for SEVIRI
  testinput_tier_1/seviriclr.odb
  testinput_tier_1/test_reference/test-SEVIRIClr.hdf
Labels: ready for merge

#169 Fix to handle vector values in attributes
  testinput_tier_1/gnssro_obs_2021080606_s.nc4
  testinput_tier_1/test_reference/gnssro_obs_2021080606_s_time_reader_pool.nc4
Labels: INFRA

#168 Assign input file location indices to Location variable
  testinput_tier_1/test_reference/amsua_n19_obs_2018041500_m_time.nc4
  testinput_tier_1/test_reference/amsua_n19_obs_2018041500_m_time_reader_pool.nc4
  testinput_tier_1/test_reference/dist_write_atlas_out.nc4
  testinput_tier_1/test_reference/dist_write_halo_out.nc4
  testinput_tier_1/test_reference/dist_write_inefficient_out.nc4
  testinput_tier_1/test_reference/dist_write_round_robin_out.nc4
  testinput_tier_1/test_reference/gnssro_obs_2021080606_s_time_reader_pool.nc4
  testinput_tier_1/test_reference/io_pool_sondes_multi_out_0000.nc4
  testinput_tier_1/test_reference/io_pool_sondes_multi_out_0001.nc4
  testinput_tier_1/test_reference/io_pool_sondes_multi_out_0002.nc4
  testinput_tier_1/test_reference/io_pool_sondes_multi_out_0003.nc4
  testinput_tier_1/test_reference/io_pool_sondes_single_out.nc4
  testinput_tier_1/test_reference/ioda_writer_sondes.nc4
  testinput_tier_1/test_reference/out_dims_check.nc4
  testinput_tier_1/test_reference/sondes_obs_2018041500_m_time.nc4
  testinput_tier_1/test_reference/sondes_obs_2018041500_m_time_reader_pool.nc4
Labels: INFRA

#171 Bugfix: ODB write for arrays of size Channel*Location
  testinput_tier_1/test_reference/diagout-iasi_0000.odc
Labels: needs review, coordinate merge, UKMO

#170 Remove the incoming NAME attribute value on the Location variable
  testinput_tier_1/test_reference/gnssro_obs_2021080606_s_time.nc4
Labels: INFRA
