Repository JCSDA-internal/ioda-data, pull requests merged in 2024-08, with the labels that each got.

#197 Test files for ObsSpace::append
  testinput_tier_1/test_append1/obsspace_append_1D.nc4
  testinput_tier_1/test_append1/obsspace_append_2D.nc4
  testinput_tier_1/test_append1/obsspace_append_no_obserror.nc4
  testinput_tier_1/test_append2/obsspace_append_1D.nc4
  testinput_tier_1/test_append2/obsspace_append_2D.nc4
  testinput_tier_1/test_append2/obsspace_append_no_obserror.nc4
  testinput_tier_1/test_append3/obsspace_append_1D.nc4
  testinput_tier_1/test_append3/obsspace_append_2D.nc4
  testinput_tier_1/test_append3/obsspace_append_no_obserror.nc4
  testinput_tier_1/test_reference/obsspace_append_1D_out.nc4
  testinput_tier_1/test_reference/obsspace_append_2D_out.nc4
  testinput_tier_1/test_reference/obsspace_append_no_obserror_out.nc4
Labels: ALGO

#198 Increase cmake_minimum_required to 3.12
  CMakeLists.txt
Labels: ready for merge

#199 Radar Doppler wind and reflectivity test files
  testinput_tier_1/radar_doppler_wind.odb
  testinput_tier_1/radar_reflectivity.odb
  testinput_tier_1/test_reference/test-RadarDopplerWind.hdf
  testinput_tier_1/test_reference/test-RadarReflectivity.hdf
Labels: UKMO

#200 Do not read observations with missing observation value
  testinput_tier_1/oceancol.odb
  testinput_tier_1/test_reference/test-OceanColour.hdf
Labels: UKMO
